-- 회원과 권한 관련

-- 회원 정보
CREATE TABLE CP_USER(
	USER_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	USERNAME VARCHAR2(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR2(255) NOT NULL,
	NICKNAME NVARCHAR2(10) NOT NULL UNIQUE,
	REALNAME VARCHAR2(30) NOT NULL,	
	EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	ROLE VARCHAR2(15) DEFAULT 'ROLE_USER' CHECK (ROLE IN ('ROLE_USER', 'ROLE_ADMIN')) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')) NOT NULL
);
SELECT * FROM CP_USER;

COMMIT;
-- 회원 활동 포인트 변동 정보
CREATE TABLE CP_POINT_HISTORY(
	HISTORY_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	REVIEW_NO NUMBER NOT NULL,
	POINT_CHANGE NUMBER NOT NULL,
	REASON VARCHAR2(255) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT FK_POINT_HISTORY_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO) ON DELETE CASCADE,
	CONSTRAINT FK_POINT_HISTORY_REVIEW_NO FOREIGN KEY (REVIEW_NO) REFERENCES CP_REVIEW(REVIEW_NO) ON DELETE CASCADE
);
SELECT * FROM CP_POINT_HISTORY;
INSERT INTO CP_POINT_HISTORY 
(USER_NO,REVIEW_NO,POINT_CHANGE,REASON)
VALUES (61,84,100,'가나다라');

-- 회원 활동 포인트와 등급 정보
CREATE TABLE CP_POINT(
	USER_NO NUMBER NOT NULL UNIQUE,
	POINT NUMBER DEFAULT 0 NOT NULL,
	USER_LEVEL NVARCHAR2(10) DEFAULT '뚜벅이' CHECK (USER_LEVEL IN ('뚜벅이', '운전자', '마스터', '챔피언')) NOT NULL,
	CONSTRAINT FK_POINT_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO) ON DELETE CASCADE
);
SELECT * FROM CP_POINT ;

-- 회원 프로필 사진 정보
CREATE TABLE CP_USER_IMG(
	USER_NO NUMBER NOT NULL UNIQUE,
	IMG_URL VARCHAR2(255) NOT NULL,
	CONSTRAINT FK_USER_IMG_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO) ON DELETE CASCADE
);


-- 게시판 1: 리뷰

-- 리뷰 게시판 정보
CREATE TABLE CP_REVIEW(
	REVIEW_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	TITLE NVARCHAR2(50) NOT NULL,
	CONTENT NVARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	COUNT NUMBER DEFAULT 0 NOT NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')) NOT NULL
	CONSTRAINT FK_REVIEW_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO)
);

INSERT INTO CP_REVIEW (USER_NO,TITLE,CONTENT)
VALUES (61,'리뷰게시판','테스트');

SELECT * FROM CP_REVIEW ;

-- 리뷰 게시물 첨부 파일 정보
CREATE TABLE CP_RV_FILE(
	FILE_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	FILE_URL VARCHAR2(255) NOT NULL UNIQUE,
	REVIEW_NO NUMBER NOT NULL,
	CONSTRAINT FK_FILE_REVIEW_NO FOREIGN KEY (REVIEW_NO) REFERENCES CP_REVIEW(REVIEW_NO) ON DELETE CASCADE
);
INSERT INTO CP_RV_FILE (FILE_URL,REVIEW_NO)
VALUES ('/uploads/report12346_image.png',21);

SELECT * FROM CP_RV_FILE ;

COMMIT;
SELECT USER_NO userNo, USERNAME, PASSWORD, NICKNAME, REALNAME, EMAIL, ROLE FROM CP_USER WHERE USERNAME = 'cptest7342';
SELECT P.USER_NO, 
H.REVIEW_NO, 
U.USERNAME, 
U.REALNAME, 
P.USER_LEVEL, 
H.REASON, 
H.POINT_CHANGE, 
P.POINT, 
H.CREATE_DATE 
FROM CP_POINT_HISTORY H 
LEFT JOIN CP_POINT P ON H.USER_NO = P.USER_NO 
LEFT JOIN CP_USER U ON P.USER_NO = U.USER_NO 
WHERE U.USERNAME = 'cptest7342' 
ORDER BY CREATE_DATE DESC;
SELECT * FROM CP_point;
SELECT * FROM CP_POINT_HISTORY;

-- 리뷰 게시물 추천 개수 정보
CREATE TABLE CP_LIKE(
	USER_NO NUMBER NOT NULL,
	REVIEW_NO NUMBER NOT NULL,
	CONSTRAINT FK_LIKE_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO),
	CONSTRAINT FK_LIKE_REVIEW_NO FOREIGN KEY (REVIEW_NO) REFERENCES CP_REVIEW(REVIEW_NO) ON DELETE CASCADE
);

-- 리뷰 게시물 댓글 정보
CREATE TABLE CP_RV_COMMENT(
	COMMENT_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	REVIEW_NO NUMBER NOT NULL,
	USER_NO NUMBER NOT NULL,
	CONTENT NVARCHAR2(300) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')) NOT NULL
	CONSTRAINT FK_COMMENT_REVIEW_NO FOREIGN KEY (REVIEW_NO) REFERENCES CP_REVIEW(REVIEW_NO) ON DELETE CASCADE,
	CONSTRAINT FK_COMMENT_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO)
);
INSERT INTO CP_RV_COMMENT (REVIEW_NO,USER_NO,CONTENT)
VALUES (21,61,'댓글테스트');
SELECT * FROM CP_RV_COMMENT ;
-- 게시판 2: 공지사항

-- 공지사항 정보
CREATE TABLE CP_NOTICE(
	NOTICE_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	TITLE NVARCHAR2(50) NOT NULL,
	CONTENT NVARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	COUNT NUMBER DEFAULT 0 NOT NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')) NOT NULL
	CONSTRAINT FK_NOTICE_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO)
);
SELECT * FROM CP_NOTICE ;
INSERT INTO CP_NOTICE (USER_NO,TITLE,CONTENT)
VALUES (61,'공지사항','댓글 테스트');


-- 공지사항 첨부 파일 정보
CREATE TABLE CP_NT_FILE(
	FILE_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	FILE_URL VARCHAR2(255) NOT NULL UNIQUE,
	NOTICE_NO NUMBER NOT NULL,
	CONSTRAINT FK_FILE_NOTICE_NO FOREIGN KEY (NOTICE_NO) REFERENCES CP_NOTICE(NOTICE_NO) ON DELETE CASCADE
);
INSERT INTO CP_NT_FILE (FILE_URL,REPORT_NO)
VALUES('/uploads/report1234_image.png',24);

-- 공지사항 댓글 정보
CREATE TABLE CP_NT_COMMENT(
	COMMENT_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	NOTICE_NO NUMBER NOT NULL,
	USER_NO NUMBER NOT NULL,
	CONTENT NVARCHAR2(300) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')) NOT NULL
	CONSTRAINT FK_COMMENT_NOTICE_NO FOREIGN KEY (NOTICE_NO) REFERENCES CP_NOTICE(NOTICE_NO) ON DELETE CASCADE,
	CONSTRAINT FK_COMMENT_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO)
);

SELECT * FROM CP_NT_COMMENT ;
INSERT INTO CP_NT_COMMENT (NOTICE_NO,USER_NO,CONTENT)
VALUES (22,61,'테스트');

COMMIT;

-- 게시판 3: 신고/문의

-- 신고/문의 게시판 정보
CREATE TABLE CP_REPORT(
	REPORT_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	TITLE NVARCHAR2(50) NOT NULL,
	CONTENT NVARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	COUNT NUMBER DEFAULT 0 NOT NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')) NOT NULL
	CONSTRAINT FK_REPORT_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO)
);
INSERT INTO CP_REPORT (USER_NO,TITLE,CONTENT)
VALUES(61,'타이틀 테스트2','컨텐트 테이트2');


SELECT *FROM CP_REPORT ;
COMMIT;

-- 신고/문의 게시물 첨부 파일 정보
CREATE TABLE CP_RP_FILE(
	FILE_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	FILE_URL VARCHAR2(255) NOT NULL UNIQUE,
	REPORT_NO NUMBER NOT NULL,
	CONSTRAINT FK_FILE_REPORT_NO FOREIGN KEY (REPORT_NO) REFERENCES CP_REPORT(REPORT_NO) ON DELETE CASCADE
);
INSERT INTO CP_RP_FILE (FILE_URL,REPORT_NO)
VALUES('/uploads/report1234_image.png',24);

SELECT *FROM CP_RP_FILE ;
-- 신고/문의 게시물 댓글 정보
CREATE TABLE CP_PR_COMMENT(
	COMMENT_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	REPORT_NO NUMBER NOT NULL,
	USER_NO NUMBER NOT NULL,
	CONTENT NVARCHAR2(300) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')) NOT NULL
	CONSTRAINT FK_COMMENT_REPORT_NO FOREIGN KEY (REPORT_NO) REFERENCES CP_REPORT(REPORT_NO) ON DELETE CASCADE,
	CONSTRAINT FK_COMMENT_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO)
);

-- 렌트 차량 모델 정보
CREATE TABLE CP_RENTAL_CAR_MODEL(
	MODEL_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	CAR_MODEL NVARCHAR2(50) NOT NULL UNIQUE,
	RENT_PRICE NUMBER NOT NULL,
	HOUR_PRICE NUMBER NOT NULL,
	CHARGE_TYPE NVARCHAR2(30) NOT NULL,
	SEAT_COUNT NUMBER NOT NULL,
	CAR_IMG_URL VARCHAR2(255) NOT NULL
);

INSERT INTO CP_RENTAL_CAR_MODEL (CAR_MODEL,RENT_PRICE,HOUR_PRICE,CHARGE_TYPE,SEAT_COUNT,CAR_IMG_URL)
VALUES ('KH테슬라',123,1234,'충전기',4,'https://www.example.com/images/tesla.jpg');
SELECT * FROM CP_RENTAL_CAR_MODEL;


-- 주차장 정보
CREATE TABLE CP_PARKING_INFO(
	PARKING_ID VARCHAR2(255) PRIMARY KEY,
	PARKING_TITLE NVARCHAR2(50) NOT NULL,
	PARKING_ADDR NVARCHAR2(255) NOT NULL,
	LAT VARCHAR2(30) NOT NULL,
	LOT VARCHAR2(30) NOT NULL
);
INSERT INTO CP_PARKING_INFO (PARKING_ID,PARKING_TITLE,PARKING_ADDR,LAT,LOT)
VALUES ('abc123','KH주차장','종각역','TEST','TEST');
DELETE FROM CP_PARKING_INFO WHERE PARKING_ID = 'abc123';
SELECT * FROM CP_PARKING_INFO WHERE PARKING_ID = 'abc123';
SELECT * FROM CP_PARKING_INFO;

-- 차량 정보
CREATE TABLE CP_RENTAL_CAR(
	CAR_NO NUMBER GENERATED AS IDENTITY PRIMARY KEY,
	CAR_ID NVARCHAR2(8) UNIQUE,
	MODEL_NO NUMBER NOT NULL,
	PARKING_ID VARCHAR2(255) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT FK_CAR_MODEL_NO FOREIGN KEY (MODEL_NO) REFERENCES CP_RENTAL_CAR_MODEL(MODEL_NO) ON DELETE CASCADE,
	CONSTRAINT FK_CAR_PARKING_ID FOREIGN KEY (PARKING_ID) REFERENCES CP_PARKING_INFO(PARKING_ID)
);
INSERT INTO CP_RENTAL_CAR (CAR_ID,MODEL_NO,PARKING_ID)
VALUES ('31가9864',62,'1583447');


SELECT * FROM CP_RENTAL_CAR ;

-- 예약 관리
CREATE TABLE CP_RENTAL_RESERVATION(
	RESERVATION_NO NUMBER PRIMARY KEY,
	USER_NO NUMBER NOT NULL,
	CAR_NO NUMBER NOT NULL,
	RENTAL_DATE DATE NOT NULL,
	RETURN_DATE DATE NOT NULL,
	TOTAL_PRICE NUMBER NOT NULL,
	STATUS VARCHAR2(20) NOT NULL, -- 결제 상태
	IMP_UID VARCHAR2(100) NOT NULL,
	PAYMENT_COMPLETED_AT DATE NOT NULL,
	CONSTRAINT FK_RESERVATION_USER_NO FOREIGN KEY (USER_NO) REFERENCES CP_USER(USER_NO) ON DELETE CASCADE,
	CONSTRAINT FK_RESERVATION_CAR_NO FOREIGN KEY (CAR_NO) REFERENCES CP_RENTAL_CAR(CAR_NO) ON DELETE CASCADE
);
INSERT INTO CP_RENTAL_RESERVATION 
(RESERVATION_NO,USER_NO,CAR_NO,RENTAL_DATE,RETURN_DATE,TOTAL_PRICE,STATUS,IMP_UID,PAYMENT_COMPLETED_AT)
VALUES
(5,61,41,'2025-04-25','2025-04-26',1,'결제상태','결제완료아이디','2025-04-27');

SELECT * FROM CP_RENTAL_RESERVATION;

COMMIT;
