DROP TABLE "TB_USER";

CREATE TABLE "TB_USER" (
	"USER_ID"	VARCHAR2(15)		NOT NULL,
	"USER_PW"	VARCHAR2(60)		NOT NULL,
	"USER_NAME"	VARCHAR2(20)		NOT NULL,
	"USER_EMAIL"	VARCHAR2(30)		NULL,
	"USER_PHONE"	CHAR(13)		NOT NULL,
	"USER_SSN"	CHAR(12)		NOT NULL,
	"USER_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_ROLL"	VARCHAR2(20)		NOT NULL,
	"USER_STAUTS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

INSERT INTO TB_USER VALUES ('uqse01','pass01','홍길동','hong@kh.com','010-1234-1234',
															'0011101-0010',DEFAULT,'ROLE_USER','Y');
);

DROP TABLE "TB_PRODUCT";

CREATE TABLE "TB_PRODUCT" (
	"PRODUCT_NO"	NUMBER		NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(100)		NULL,
	"PRODUCT_PRICE"	NUMBER		NULL,
	"PRODUCT_SELLER"	VARCHAR(30)		NULL,
	"PRODUCT_STOCK"	NUMBER		NULL,
	"PRODUCT_STATUS"	CHAR(1)	DEFAULT 'Y'	NULL
);

INSERT INTO TB_PRODUCT VALUES('시퀀스넘버','상품명','500000','나야나',50,'Y');



