
-- 아이디, 비밀번호, 이름, 이메일, 가입일
CREATE TABLE KH_MEMBER(
	MEMBER_ID VARCHAR2(10) PRIMARY KEY, 
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NAME VARCHAR2(15) NOT NULL,
	EMAIL VARCHAR2(50),
	ENDOLLDATE DATE DEFAULT SYSDATE
);

INSERT INTO KH_MEMBER VALUES
('admin',  1234, '짱구', 'kh01@kh.com', DEFAULT);
INSERT INTO KH_MEMBER VALUES
('user01', 1234, '맹구', 'kh02@kh.com', DEFAULT);
INSERT INTO KH_MEMBER VALUES
('user02', 1234, '유리', 'kh03@kh.com', DEFAULT);

SELECT * FROM KH_MEMBER;





CREATE SEQUENCE SEQ_KH_BOARD;

CREATE TABLE KH_BOARD(
 	BOARD_NO NUMBER PRIMARY KEY,
 	BOARD_CATEGORY VARCHAR2(20) NOT NULL,
 	BOARD_WRITER VARCHAR2(20) REFERENCES KH_MEMBER,
 	BOARD_TITLE VARCHAR2(300) NOT NULL,
 	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
 	COUNT NUMBER DEFAULT 0,
 	CREATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM  KH_BOARD;


ALTER TABLE KH_MEMBER MODIFY MEMBER_PW VARCHAR2(60);

UPDATE 	
		KH_MEMBER 
	SET 	
		MEMBER_PW = '$2a$10$SlVRwvdiRJoQd/BYTcWcieUpxx.g8yM1O87TQCDMAZd/lB5yMN7IC';

COMMIT;

SELECT *FROM  KH_MEMBER ;



-- 게시글용 테이블 구현하기
-- 파일첨부 기능 구현할 것 + 댓글 기등 구현할 것

-- 글번호
 -- 글 제목
 -- 작성자
 -- 조회수
 -- 작성일 


CREATE TABLE TB_SPRING_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	BOARD_TITLE VARCHAR2(200) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER VARCHAR2(10) NOT NULL REFERENCES KH_MEMBER,
	COUNT NUMBER DEFAULT 0 NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
	CHANGE_NAME VARCHAR2(200),
  STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);







DROP TABLE TB_SPRING_BOARD;
INSERT INTO TB_SPRING_BOARD(BOARD_TITLE, BOARD_WRITER)
VALUES('첫 번째 글', 'admin');

SELECT * FROM TB_SPRING_BOARD;













